include:
  - project: "tulibraries/gitlab-ci-templates"
    file:
      - "lint_docker.yaml"
      - "build_docker.yaml"
      - "security_scan.yaml"
    ref: fix-slow-scan-issue

before_script:
  - source .env
  - export TAG="${DOCKER_IMAGE_VERSION}"
  - export VERSION="${DOCKER_IMAGE_VERSION}-${CI_COMMIT_SHORT_SHA}"

variables:
  IMAGE: "tulibraries/git-sync"

stages:
  - lint
  - build
  - scan
  - tag

lint:
  extends: .lint_docker

build:
  stage: build
  extends: .build_image

scan:
  stage: scan
  extends: .scanimage
