include:
  - project: "infrastructure-engineering-shared/gitlab-ci-templates"
    file: "lint_docker.yaml"
  - project: "infrastructure-engineering-shared/gitlab-ci-templates"
    file: "build_docker.yaml"
  - project: "infrastructure-engineering-shared/gitlab-ci-templates"
    file: "security_scan.yaml"

script:
  - "source .env"
variables:
  IMAGE: "tulibraries/git-sync"
  VERSION: "${DOCKER_IMAGE_VERSION}-${CI_BUILD_ID}"

stages:
  - lint
  - build
  - scan

lint:
  extends: .lint_docker

build:
  stage: build
  extends: .build_image


scan:
  stage: scan
  extends: .scanimage
