include:
  - project: "infrastructure-engineering-shared/gitlab-ci-templates"
    file:
      - "lint_docker.yaml"
      - "build_docker.yaml"
      - "security_scan.yaml"

variables:
  IMAGE: "tulibraries/git-sync"

before_script:
  - source .env
  - export VERSION="${DOCKER_IMAGE_VERSION}-${CI_COMMIT_SHORT_SHA}"

stages:
  - lint
  - build
  - scan
  - tag

lint:
  extends: .lint_docker

build:
  stage: build
  extends: .build_image

scan:
  stage: scan
  extends: .scanimage

tag_latest:
  stage: tag
  extends: .tag_image

tag:
  stage: tag
  variables:
    TAG: $DOCKER_IMAGE_VERSION
  extends: .tag_image
